nunnatsa/ginkgolinter

- .github/workflows/sanity.yml
- README.md
- ginkgo_linter.go
- ginkgo_linter_test.go
- testdata/src/a/b.go
- testdata/src/a/c.go
- testdata/src/a/d.go
It is now possible to suppress the wrong length check linter, iether for
a specific line, or for a whole file.
> Add option to suppress the linter

- ginkgo_linter.go
By setting the Analyzer's RunDespiteErrors field to true, the type
check is skiped and the linter can work without the need to actually
import ginkgo and gomega.
This will ease the integration with other applications, such as
golangci-lint.
> Remove all the dependencies in ginkgo & gomega

- .github/workflows/sanity.yml
- README.md
- cmd/cli.go
- ginkgo_linter.go
- ginkgo_linter_test.go
- testdata/src/a/configlen/a.go
- testdata/src/a/confignil/a.go
- testdata/src/a/len/a.go
- testdata/src/a/nil/a.go
- testdata/src/a/suppress/a.go
- testdata/src/a/suppress/b.go
- testdata/src/a/suppress/c.go
- testdata/src/a/suppress/d.go
*Add new warning when using these formats:
`Expect(x == nil).To(Equal(true))` => `Expect(x).To(BeNil())`
`Expect(x == nil).To(Equal(false))` => `Expect(x).ToNot(BeNil())`
`Expect(x == nil).To(BeTrue())` => `Expect(x).To(BeNil())`
`Expect(x == nil).To(BeFalse())` => `Expect(x).ToNot(BeNil())`
* Add two command line flags:
* suppress-len-assertion - to suppress the wrong length assertion
warning
* suppress-nil-assertion - to suppress the wrong nil assertion
warning
> Add nil check warning + command line flags

- .github/workflows/sanity.yml
- ginkgo_linter.go
- ginkgo_linter_test.go
- testdata/src/a/nodotimport/a.go
- testdata/src/a/nodotimport/b.go
- testdata/src/a/noginkgo/a.go
ginkgo documentation uses dot import; i.e.
```go
import . "github.com/onsi/gomega"
```
But the user can use impot without name or with custom name, e.g.
```go
import "github.com/onsi/gomega"
```
Or
```go
import custom "github.com/onsi/gomega"
```
This PR adds support for these two forms of importt.
Also, the linter now skips files without gomega import.
> Support different ways to import gomega

- .github/workflows/sanity.yml
- Makefile
- README.md
Some tools built ginkgo-linter and other ginkgolinter (because go does
not allow package names with '-').
Now the name is `ginkgolinter` from all the tools.
> Rename te executable

- .github/workflows/sanity.yml
- ginkgo_linter_test.go
- gomegahandler/handler.go
- testdata/src/a/gomegaonly/gomegaonly_test.go
- testdata/src/a/gomegaonly/gomegaonly_w_mod_name_test.go
- testdata/src/a/gomegaonly/gomegaonly_w_name_test.go
This PR adds support for cases when using gomega directly, without ginkgo.
For example:
```golang
func TestSomething(t *testing.T) {
g := NewGomegaWithT(t)
var err error
g.Expect(err).ToNot(BeNil())
}
```
> Support gomega without ginkgo

- ginkgo_linter.go
- go.mod
- go.sum
ginkgolinter no longer write to the ast tree, and should not fails other linters anymore. Instead, it computes the suggested fixes using a clone, from the `github.com/go-toolsmith/astcopy` package
Fixes #39
> Fix bug where ginkgolinter fails other linters

- .github/workflows/sanity.yml
- README.md
- ginkgo_linter.go
- ginkgo_linter_test.go
- testdata/src/a/havelen0/gomega.go
- testdata/src/a/havelen0/havelen0.go
- testdata/src/a/havelen0config/gomega.go
- testdata/src/a/havelen0config/havelen0.go
- types/boolean_test.go
- types/config.go
- types/config_test.go
The linter now warns for `HaveLen(0)`, and suggests using `BeEmpty()` instead
Support new parameter: `allow-havelen-0`. Default is false. If true, the linter will not warn for `HaveLen(0)`.
Fixes #46
> Add check HaveLen(0)

- ginkgo_linter_test.go
- testdata/src/a/noginkgo/a.go
To ease addition of new features and tests, move the ginkgolinter tests to be parameterized tests.
> Move to parameterized tests

- .github/workflows/sanity.yml
- README.md
- ginkgo_linter.go
- ginkgo_linter_test.go
- reverseassertion/reverse_assertion.go
- reverseassertion/reverse_assertion_test.go
- testdata/src/a/comparison/comparison.go
- testdata/src/a/comparison/comparison.gomega.go
- testdata/src/a/configcompare/a.go
- testdata/src/a/havelen0/havelen0.go
- testdata/src/a/nil/a.go
- testdata/src/a/suppress/coparison.comment.go
- testdata/src/a/suppress/coparison.file.go
- types/config.go
- types/config_test.go
A worng comparison is a boolean comparison using `==', `!=`, `>`, `>=`, `<` or `<=`, and assertion of a boolean value.
Examples:
`Expect(x == 10).Should(BeTrue())` ==> `Expect(x).Should(Equal(10))`
`Expect(s != "testing").Should(Equal(true))` ==> `Expect(s).ShouldNot(Equal("testing"))`
`Expect(x > 10).To(BeTrue())` ==> `Expect(x).To(BeNumerically(">", 10))`
Added a new executable's flag to suppress this new rule: `--suppress-compare-assertion=true`
Fixes #64 
@pohly
> Add new linter rule: avoid comparison assersion

- .github/workflows/sanity.yml
- ginkgo_linter.go
- ginkgo_linter_test.go
- testdata/src/a/pointers/pointers.go
- testdata/src/a/pointers/pointers.gomega.go
When comapring two pointrs like this:
`Expect(p1 != p2).To(BeTrue())`
For go, it means comparing the
addresses. The linter changes this to
`Expect(p1).ToNot(Equal(p2))`.
But in this case gomega compares the values
pointed by the pointers.
This PR fixes this issue by using the `BeIdenticalTo` matcher in case of pointers coparison.
@nunnatsa
> Fix bug with comparison and pointers

- .github/workflows/sanity.yml
- ginkgo_linter.go
- gomegahandler/handler.go
- testdata/src/a/boolean/bool.go
- testdata/src/a/comparison/comparison.go
- testdata/src/a/comparison/comparison.gomega.go
- testdata/src/a/equalnil/a.go
- testdata/src/a/havelen0/gomega.go
- testdata/src/a/havelen0/havelen0.go
- testdata/src/a/len/a.go
- testdata/src/a/nil/a.go
- testdata/src/a/nodotimport/a.go
- testdata/src/a/nodotimport/b.go
- testdata/src/a/pointers/pointers.go
- testdata/src/a/suppress/e.go
- testdata/src/a/suppress/f.go
The linter used to ignore patterns like
`Expect(len(x)).WithOffset(1).Should(Equal3))`. now the linter will catch these patterns as well.
> Support the WithOffset method

- .github/workflows/sanity.yml
- ginkgo_linter.go
- reverseassertion/reverse_assertion.go
- reverseassertion/reverse_assertion_test.go
- testdata/src/a/boolean/bool.go
Patterns like `Expect(boolVal).ShouldNot(Equal(false))` or `Expect(boolVal).ShouldNot(BeFalse())`, the linter will suggest `Expect(boolVal).Should(BeTrue())`
> Avoid double negative assertions

- README.md
- ginkgo_linter.go
- ginkgo_linter_test.go
- testdata/src/a/pointerval/pointerval.go
- testdata/src/a/pointerval/pointerval.gomega.go
- tests/e2e.sh
The linter warns when comparing a pointer with a value. These comparisons are always wrong and will always fail.
For example:
```go
num := 5
...
pNum := &num
...
Expect(pNum).ShouldNot(Equal(6))
```
The linter will suggest to use this instead:
```go
Expect(pNum).ShouldNot(HaveValue(Equal(6)))
```
Fixes #76 
@BorzdeG
> Add new linter rule: Compare pointer to value

- ginkgo_linter.go
- testdata/src/a/pointerval/pointerval.go
For example, the function f()'s returned type is an interfce, but it actually returns a pointer.
The linter triggered a warning for this code:
```go
Expect(somePointer).Eqaul(f())
```
But this is a actually a valid assertion.
This PR fixes this bug and does not trigger the warning the assertion compares to `types.Named`.
@nunnatsa
> bug fix: false negative when comparing a pointer and an interface

- ginkgo_linter.go
- testdata/src/a/comparison/string_non_equal.go
Fix bug where when comparing two strings with non-equal sign (e.g. `<` or `>=`), the linter wrongly triggered a warning and suggested to use `BeNumerically`.
Fixes #82
> Fix false positive for string non-equal comparison

- README.md
- ginkgo_linter.go
- ginkgo_linter_test.go
- gomegahandler/handler.go
- testdata/src/a/noassersion/ginkgo.go
- testdata/src/a/noassersion/gomagaimport.go
- testdata/src/a/noassersion/gomega_test.go
- tests/e2e.sh
The linter warns when calling an "actual" method (e.g. `Expect()`, `Eventually()` etc.), without an assertion method (e.g `Should()`, `NotTo()` etc.)
For example:
```go
// no assertion for the result
Eventually(doSomething).WithTimeout(time.Seconds * 5).WithPolling(time.Milliseconds * 100)
```
The linter will not suggest a fix for this warning.
This rule cannot be suppressed.
> New Rule: Missing Assertion Method

- ginkgo_linter.go
- testdata/src/a/eventually/eventuallyFunc.go
When calling a function that return a type in the async assertion (eventually/constantly) body, if this type is a function, the linter fails to recognize it and fire a warning.
This PR fixes this bug, by checking the underline types.
Fixes #91
@nunnatsa
> Fix bug: false positive warning for typed function calls

- .github/workflows/sanity.yml
- README.md
- ginkgo_linter.go
- ginkgo_linter_test.go
- ginkgohandler/handler.go
- ginkgohandler/handler_test.go
- testdata/src/a/focus/focus_name_test.go
- testdata/src/a/focus/focus_noname_test.go
- testdata/src/a/focus/focus_test.go
- testdata/src/a/focus/supress_test.go
- testdata/src/a/focusconfig/focus_name_test.go
- testdata/src/a/focusconfig/focus_noname_test.go
- testdata/src/a/focusconfig/focus_test.go
- tests/e2e.sh
- types/config.go
- types/config_test.go
Focus ginkgo containers (FDescribe, FContext, FWhen, and FIt) should only be used locally, on debug.
This PR introduces a new rule to prevent the leaking of this kind of debug code into the source code in the repo.
New suppress comment to suppress this new rule: `// ginkgo-linter:ignore-focus-container-warning`
New command line flag to suppress this new rule: `--suppress-focus-container`
Fixes https://github.com/kubevirt/kubevirt/issues/10120
@nunnatsa
> Add new rule: disallow focus containers

- ginkgo_linter.go
- ginkgo_linter_test.go
- tests/e2e.sh
- types/config.go
- types/config_test.go
The `--forbid-focus-container` flag behaved with the reverse logic.
This PR fixes it.
@nunnatsa
> Fix bug with the forbid-focus-container flag

- README.md
- ginkgo_linter.go
- ginkgohandler/handler.go
- testdata/src/a/focus/focus_key_test.go
- testdata/src/a/focus/table_test.go
- testdata/src/a/focusconfig/focus_key_name_test.go
- testdata/src/a/focusconfig/focus_key_test.go
- testdata/src/a/focusconfig/table_name_test.go
- testdata/src/a/focusconfig/table_test.go
- tests/e2e.sh
1. Forbid also the usage of the `Focus` individual spec, e.g.
```go
It("test something", Focus, func(){
Expect(...)...
})
```
2. Also forbid the `FDescribeTable` and the `FEntry` focused containers.
@nunnatsa
> Improve focus rule

- README.md
- ginkgo_linter.go
- ginkgo_linter_test.go
- testdata/src/a/comparetypes/comparetypes.gomega_test.go
- testdata/src/a/comparetypes/comparetypes_test.go
- testdata/src/a/comparetypesconfig/comparetypes.gomega_test.go
- testdata/src/a/comparetypesconfig/comparetypes_test.go
- testdata/src/a/pointerval/pointerval.go
- testdata/src/a/suppress/f.go
- testdata/src/a/suppress/typecompare_all.go
- testdata/src/a/suppress/typecompare_comment.go
- tests/e2e.sh
- types/config.go
The `Equal` and the `BeIdentical` matchers also check the type, not only the value.
The following code will fail in runtime:
```go
x := 5 // x is int
Expect(x).Should(Eqaul(uint(5)) // x and uint(5) are with different
types
```
When using negative checks, it's even worse, because we get a fale positive:
```
x := 5
Expect(x).ToNot(Equal(uint(5))
```
To solve this problem, we want to find these errors before running the tests and failing on runtime. This is even more important for e2e or functional tests, where we sometimes can't run them on the local development environment.
This PR adds a new rule to the linter, to find comaprison of values from different types.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any …
> New Rule: should not compare two different types

- ginkgo_linter.go
- testdata/src/a/comparetypes/comparetypes_test.go
- tests/e2e.sh
The `WithTransform` matcher can be used to transform the actual value type. This PR fix a false positive when using this matcher to change the actual value type to match the matcher type.
For example:
```go
Expect(uint(5)).Should(WithTransform(func(i uint) int { return int(i) }, Equal(5)))
```
In this case, the test should work because the transform function (the first parameter of the `WithTransform` matcher) casts the `uint` actual value to `int`, to match the `Equal(5)` matcher.
@nunnatsa
> Fix the compare different type rule, to allow using WithTransform

- ginkgo_linter.go
- testdata/src/a/comparetypes/comparetypes.gomega_test.go
- testdata/src/a/comparetypes/comparetypes_test.go
- tests/e2e.sh
The bug is that when checking the comparison of two different types, if the matcher is `WithTransform`, ginkgo linter does not check the nested matcher, causing false positive for any matcher other than `Equal` or `BeIdentical`.
This PR fixes this issue by checking the nested matcher name, and only trigger error if the nested matcher is `Equal` or `BeIdentical`.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #115
@nunnatsa
> Fix issue with comparing different types and WithTransform

- .github/workflows/sanity.yml
- go.mod
Downgrade to go1.20 because golangci-lint does not support go1.21, yet
@nunnatsa
> downgrade to go1.20 because golangci-lint does not support go1.21, yet

- README.md
- doc.go
- ginkgo_linter.go
- ginkgo_linter_test.go
- gomegahandler/handler.go
- testdata/src/a/forceExpectTo/gomegavar.go
- testdata/src/a/forceExpectTo/nodotimport.go
- testdata/src/a/forceExpectTo/simple.go
- tests/e2e.sh
- types/config.go
Added new rule: should not use `Expect` with the `Should` or `ShouldNot` assertion methods.
This rule is not enabled by default. To enable it, use the `--force-expect-to=true` flag.
The new rule does support auto fix.
Fixes #112 
@nunnatsa
> Add new optional rule: force `Expect` with `To`

- README.md
- analyzer_test.go
- doc.go
- linter/ginkgo_linter.go
- testdata/src/a/cap/cap.ginkgo.go
- testdata/src/a/cap/cap.go
- testdata/src/a/cap/mix-with-len.go
- testdata/src/a/cap/suppress-expr.go
- testdata/src/a/cap/suppress-file.go
- testdata/src/a/configlen/a.go
- tests/e2e.sh
Trigger warnings for directly assert the builtin `cap` function.
For example:
```go
Expect(cap(slice)).To(Equal(10)) ==> Expect(slice).To(HaveCap(10))
Expect(cap(slice) == 10).To(BeTrue()) ==> Expect(slice).To(HaveCap(10))
```
> New Rule: cap assertion

- README.md
- analyzer.go
- analyzer_test.go
- doc.go
- internal/ginkgohandler/handler.go
- internal/types/config.go
- linter/ginkgo_linter.go
- testdata/src/a/containers-vas-and-focus/containers.go
- testdata/src/a/vars-in-containers/all_containers.go
- testdata/src/a/vars-in-containers/vars.go
- testdata/src/a/vars-in-containers/vars_ginkgo.go
- tests/e2e.sh
Does not allow variable assignments in container nodes. See here for more details: https://onsi.github.io/ginkgo/#avoid-spec-pollution-dont-initialize-variables-in-container-nodes
This rule is disabled by default. use the `--forbid-spec-pollution=true` flag to enable it.
For example, this code will trigger a warning:
```go
var _ = Describe("description", func(){
var x = 10
...
})
```
Instead, use `BeforeEach()`; e.g.
```go
var _ = Describe("description", func (){
var x int
BeforeEach(func (){
x = 10
})
...
})
```
Closes: #136 
> New Rule: Avoid spec Pollution

- linter/ginkgo_linter.go
- testdata/src/a/vars-in-containers/all_containers.go
- testdata/src/a/vars-in-containers/vars.go
Avoid trigger warning for underscore assignments in node containers; e.g.
```golang
Describe("example", func() {
_ = funcReturnSomeValueEGError()
})
```
> Allow underscore assignments in node containers

- README.md
- analyzer.go
- analyzer_test.go
- doc.go
- internal/expression/actual/actual.go
- internal/expression/actual/actualarg.go
- internal/expression/actual/asyncfuncarg.go
- internal/expression/expression.go
- internal/expression/matcher/matcher.go
- internal/expression/matcher/matcherinfo.go
- internal/gomegahandler/handler.go
- internal/rules/asyncsucceedrule.go
- internal/rules/haveoccurredrule.go
- internal/rules/rule.go
- internal/rules/succeedrule.go
- testdata/src/a/confighaveoccurred/haveoccurred.go
- testdata/src/a/confighaveoccurred/haveoccurred.gomega.go
- testdata/src/a/haveoccurred/asyncsucceed.go
- testdata/src/a/haveoccurred/asyncsucceed.gomega.go
- testdata/src/a/haveoccurred/haveoccurred.go
- testdata/src/a/haveoccurred/haveoccurred.gomega.go
- tests/e2e.sh
- types/config.go
* Makes sure the `Succeed()` matcher only accepts a single error value, or a function that recieves a Gomega object as its first parameter, in async assertions.
For example: 
``` go
func retErr() error {
return errors.New(error)
}
func retValAndErr() (int, error) {
return 42, errors.New(error)
}
...
// valid
Expect(retErr()).To(Succeed())
Eventually(func(g Gomega) {
v, err := retValAndErr()
g.Expect(err).ToNot(HaveOccurred())
g.Expect(v).To(Equal(42))
}).To(Succeed())
// invalid
Expect(retValAndErr()).To(Succeed())
Eventually(func() int {return 42}).To(Succeed())
```
* force usage of `Succeed` for functions, and `HaveOccurred` for values; only applied if the new command line flag: `--force-succeed=true`, is set (default: no set).
for example:
```go
Expect(retErr()).To(HaveOccurred()) ==> …
```
> Add two new rules, to validate the `Success` and `HaveOccurred` matchers

- analyzer_test.go
- internal/expression/actual/actual.go
- internal/expression/actual/actualarg.go
- internal/expression/expression.go
- internal/gomegahandler/dothandler.go
- internal/gomegahandler/handler.go
- internal/gomegahandler/namedhandler.go
- testdata/src/a/issue-173/issue173.go
- testdata/src/a/issue-174/issue174.go
The linter triggers a warning for this case:
```go
func errFunc() func() error {
return func() error {
return errors.New("error")
}
}
var _ = Describe("test if issue 174 was solved", func() {
It("should not trigger", func() {
Eventually(errFunc()).Should(MatchError(ContainSubstring("error")))
})
})
```
The linter fails to identify the actual value as error value.
Fixes #174
as in:
```go
Expect(func() (int, error) {return 42, nil}()).Error().ToNot(HaveOccurred())
```
Fixes #173 
> Fix two bugs: 173 and 174

- go.mod
The min Go version is a hard requirement for lib consumers.
This version defines the minimum language version, so patch versions are globally useless in this case.
The Go version inside `toolchain` defined the Go version used to compile and doesn't affect lib consumers.
Revert go.mod changes from #172
@nunnatsa
> fix: downgrade min Go

- README.md
- doc.go
- docs/CONTRIBUTING.md
Corrects grammar mistakes in `README.md`, `CONTRIBUTING.md` and `docs/doc.go`.
`Constantly` changed to `Consistently`.
@nunnatsa
> fix typos in docs

- internal/expression/value/value.go
- testdata/src/a/haveoccurred/haveoccurred.go
When using a pointer as an error, like in:
```go
type myErr struct {
code int
}
func (e *myErr) Error() string {
...
}
...
err = &myErr{code: 404}
Expect(err).To(HaveOccured())
```
ginkgolinter mistakely detects `err` as not error type.
This PR fixes this issue.
Fixes #183
Originally found here: https://github.com/containernetworking/cni/issues/1148
> Fix false positive when asserting an error pointer

- internal/gomegainfo/gomegainfo.go
Don't check non ast.Ident expressions for been Gomega variables.
Make more accurate check for the Gomega types (struct or interface). check the alias value instead of the alias.
Got a bit better performance.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
> Improve IsGomegaVar() and IsGomegaType()

- analyzer_test.go
- internal/expression/actual/actualarg.go
- internal/ginkgoinfo/ginkgoinfo.go
- testdata/src/a/issue-190/issue190.go
- testdata/src/a/issue-190/issue190.gomega.go
ginkgolinter fails to recognized ginkgo.SpecContext as a valid context in Eventually, and so wrongly identify it as the actual value, instead of the following function parameter.
This PR fixes the issue and now this scenarion works
```go
It("should work", func(ctx SpecContext) {
Eventually(func() error {
return fmt.Errorf("foo")
}).WithContext(ctx).Should(MatchError("foo"))
}, SpecTimeout(time.Second))
```
Fixes #190
> Fix issue: failed to recognize ginkgo.SpecContext in Eventually
